"""table workflow_table add field is_default

Revision ID: 09d79f13798e
Revises: eae01f429e77
Create Date: 2025-01-13 16:03:15.837271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09d79f13798e'
down_revision: Union[str, None] = 'eae01f429e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_table', sa.Column('is_default', sa.Integer(), nullable=True, comment='是否为dafault'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_table', 'is_default')
    # ### end Alembic commands ###
