"""add new column type  to existing table model_type_table 

Revision ID: 8613466359aa
Revises: 0048b6032894
Create Date: 2025-01-06 14:11:27.067730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8613466359aa'
down_revision: Union[str, None] = '0048b6032894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_type_table', sa.Column('type', sa.Integer(), nullable=True, comment='服务类型,1:OCR,2:LLM'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_type_table', 'type')
    # ### end Alembic commands ###
