"""table ModelServiceTypeMode,model_type_table add field is_dafault set colum long

Revision ID: eae01f429e77
Revises: 8613466359aa
Create Date: 2025-01-10 08:38:25.491936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae01f429e77'
down_revision: Union[str, None] = '8613466359aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_type_table', sa.Column('is_default', sa.Integer(), nullable=True, comment='是否为dafault'))
    op.alter_column('model_type_table', 'description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_comment='任务描述',
               existing_nullable=True)
    op.add_column('modelservice', sa.Column('is_default', sa.Integer(), nullable=True, comment='是否为dafault'))
    op.alter_column('modelservice', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_comment='任务名',
               existing_nullable=False)
    op.alter_column('modelservice', 'description',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_comment='任务描述',
               existing_nullable=False)
    op.alter_column('modelservice', 'img_path',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_comment='图片路径',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelservice', 'img_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_comment='图片路径',
               existing_nullable=True)
    op.alter_column('modelservice', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_comment='任务描述',
               existing_nullable=False)
    op.alter_column('modelservice', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_comment='任务名',
               existing_nullable=False)
    op.drop_column('modelservice', 'is_default')
    op.alter_column('model_type_table', 'description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_comment='任务描述',
               existing_nullable=True)
    op.drop_column('model_type_table', 'is_default')
    # ### end Alembic commands ###
