version: '3.8'

services:
  template_v1.0_app:
    # 应用服务
    # build:
    #   # 使用当前目录下的Dockerfile构建镜像
    #   context: .
    #   dockerfile: dockerfile
    image: template_v1.0 # 替换为你的镜像名称
    container_name: template_v1.0_app # 设置容器名称
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # 挂载宿主机 Docker 套接字
      - /app/_internal/data/uploads/templates/:/app/_internal/data/uploads/templates/
      - /app/_internal/config:/app/_internal/config

    ports:
      - "8000:8000" # 将容器内的80端口映射到宿主机的80端口
    command: [ "/bin/sh", "-c", "/app/http_server/http_server /app/app.db" ] # 设置容器启动时执行的命令

networks:
  app_network:
    driver: bridge

volumes: {}
